### ISSUE TITLE
خ

### ISSUE THREAD

**Issue by oscarmejia1776** [AlanChen4/Summer-2024-SWE-Internships#9]
اشسءصمح لحج
صح

**Comment by AlanChen4** [comment]
Thanks for your interest in this project! I'm having difficulty understanding your message due to the language barrier. If possible, could you please restate your issue in English or provide a clearer explanation? This would greatly help me to understand and address your concerns more effectively. 

Thanks!

**Comment by ruhiiii** [comment]
Hi! Sorry for the confusion. I was just trying to subscribe to the
repository so I could get notifications when new positions are added.
